---
fixtures:
#Currently, these module versions are managed independently of the control project's Puppetfile
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    elasticsearch: "https://github.com/elastic/puppet-elasticsearch.git"
  symlinks:
    wwt_elasticsearch: "#{source_dir}"
